// Command gentables generates asm/tables.s: the 0x88 difference-indexed
// attack and direction tables, castling-rights masks, and piece offset
// tables. Run via `make tables` (or `go run ./cmd/gentables` directly).
//
// Difference tables are indexed by (to - from + $77) & $FF for squares in
// 0x88 coordinates. ATTACKTAB holds a bitmask of piece kinds that could
// attack across that difference on an empty board; DELTATAB holds the
// single-step delta (as an unsigned byte) toward `to` for slider rays,
// or 0 if the difference is not on any ray.
package main

import (
	"fmt"
	"math/rand/v2"
	"os"
	"strings"
)

const (
	atkKnight    = 1 << 0
	atkKing      = 1 << 1
	atkDiag      = 1 << 2 // bishop or queen
	atkOrtho     = 1 << 3 // rook or queen
	atkWPawn     = 1 << 4 // white pawn capture (moving up: +$0F/+$11)
	atkBPawn     = 1 << 5 // black pawn capture (moving down: -$0F/-$11)
	tableComment = "; Generated by cmd/gentables. DO NOT EDIT.\n"
)

var (
	knightOffs = []int{-33, -31, -18, -14, 14, 18, 31, 33}
	kingOffs   = []int{-17, -16, -15, -1, 1, 15, 16, 17}
	diagOffs   = []int{-17, -15, 15, 17}
	orthoOffs  = []int{-16, -1, 1, 16}
)

func onBoard(sq int) bool { return sq >= 0 && sq < 128 && sq&0x88 == 0 }

func main() {
	var attack [256]byte
	var delta [256]byte

	for from := range 128 {
		if !onBoard(from) {
			continue
		}
		mark := func(to int, bit byte, step int) {
			if !onBoard(to) {
				return
			}
			idx := (to - from + 0x77) & 0xFF
			attack[idx] |= bit
			if step != 0 {
				delta[idx] = byte(step & 0xFF)
			}
		}
		for _, o := range knightOffs {
			mark(from+o, atkKnight, 0)
		}
		for _, o := range kingOffs {
			mark(from+o, atkKing, 0)
		}
		for _, o := range diagOffs {
			for to := from + o; onBoard(to); to += o {
				mark(to, atkDiag, o)
			}
		}
		for _, o := range orthoOffs {
			for to := from + o; onBoard(to); to += o {
				mark(to, atkOrtho, o)
			}
		}
		mark(from+0x0F, atkWPawn, 0)
		mark(from+0x11, atkWPawn, 0)
		mark(from-0x0F, atkBPawn, 0)
		mark(from-0x11, atkBPawn, 0)
	}

	// Castling-rights mask: rights bits to KEEP when a square is touched
	// (moved from or captured on). Bits: 1=WK, 2=WQ, 4=BK, 8=BQ.
	var castleMask [128]byte
	for i := range castleMask {
		castleMask[i] = 0x0F
	}
	castleMask[0x04] = 0x0C // e1: white loses both
	castleMask[0x00] = 0x0D // a1: white loses queenside
	castleMask[0x07] = 0x0E // h1: white loses kingside
	castleMask[0x74] = 0x03 // e8: black loses both
	castleMask[0x70] = 0x07 // a8: black loses queenside
	castleMask[0x77] = 0x0B // h8: black loses kingside

	var b strings.Builder
	b.WriteString(tableComment)
	b.WriteString("\n.segment \"TABLES\"\n\n.align 256\n")
	emit(&b, "ATTACKTAB", attack[:])
	b.WriteString("\n.align 256\n")
	emit(&b, "DELTATAB", delta[:])
	b.WriteString("\n.align 128\n")
	emit(&b, "CASTLEMASK", castleMask[:])
	b.WriteString("\n")
	emitInts(&b, "KNIGHTOFF", knightOffs)
	emitInts(&b, "KINGOFF", kingOffs)
	emitInts(&b, "DIAGOFF", diagOffs)
	emitInts(&b, "ORTHOOFF", orthoOffs)
	emitPSQT(&b)
	emitZobrist(&b)

	if err := os.WriteFile("asm/tables.s", []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func emit(b *strings.Builder, name string, data []byte) {
	fmt.Fprintf(b, "%s:\n", name)
	for i := 0; i < len(data); i += 16 {
		b.WriteString("        .byte ")
		for j := i; j < i+16 && j < len(data); j++ {
			if j > i {
				b.WriteString(",")
			}
			fmt.Fprintf(b, "$%02X", data[j])
		}
		b.WriteString("\n")
	}
}

// emitPSQT writes the tapered piece-square tables in the engine's layout:
// for piece type t (1-6), a 512-byte block at PSQTBASE+(t-1)*512 holding
// MGLO[sq88] at +0, MGHI at +128, EGLO at +256, EGHI at +384. Values are
// white-POV with piece base values baked in; black uses sq^$70 and
// subtracts. TYPEPAGE0/1 give each type's table page for (zp),y access;
// they are emitted as link-time expressions on PSQTBASE.
func emitPSQT(b *strings.Builder) {
	b.WriteString("\n.align 256\nPSQTBASE:\n")
	for t := range 6 {
		var mglo, mghi, eglo, eghi [128]byte
		for sq := range 128 {
			if sq&0x88 != 0 {
				continue
			}
			rank := sq >> 4
			file := sq & 7
			idx := (7-rank)*8 + file // PeSTO tables are a8-first
			mg := pestoPieceMG[t] + pestoMG[t][idx]
			eg := pestoPieceEG[t] + pestoEG[t][idx]
			mglo[sq] = byte(mg & 0xFF)
			mghi[sq] = byte(mg >> 8 & 0xFF)
			eglo[sq] = byte(eg & 0xFF)
			eghi[sq] = byte(eg >> 8 & 0xFF)
		}
		names := []string{"PAWN", "KNIGHT", "BISHOP", "ROOK", "QUEEN", "KING"}
		emit(b, fmt.Sprintf("PSQT_%s_MGLO", names[t]), mglo[:])
		emit(b, fmt.Sprintf("PSQT_%s_MGHI", names[t]), mghi[:])
		emit(b, fmt.Sprintf("PSQT_%s_EGLO", names[t]), eglo[:])
		emit(b, fmt.Sprintf("PSQT_%s_EGHI", names[t]), eghi[:])
	}
	// Table page pointers, indexed by piece type 1-6 (0 and 7 unused).
	b.WriteString("\nTYPEPAGE0:\n        .byte 0")
	for t := range 6 {
		fmt.Fprintf(b, ", >PSQTBASE+%d", t*2)
	}
	b.WriteString(", 0\nTYPEPAGE1:\n        .byte 0")
	for t := range 6 {
		fmt.Fprintf(b, ", >PSQTBASE+%d", t*2+1)
	}
	b.WriteString(", 0\n")
	// Phase contribution per piece type, and phase -> /32 taper weight.
	b.WriteString("PHASEVAL:\n        .byte 0,0,1,1,2,4,0,0\n")
	b.WriteString("PHASEW:\n        .byte ")
	for p := 0; p <= 24; p++ {
		if p > 0 {
			b.WriteString(",")
		}
		fmt.Fprintf(b, "%d", (p*32+12)/24)
	}
	b.WriteString("\n")
}

// emitZobrist writes 32-bit Zobrist keys as four byte-planes, each
// [12][128] (kind-major: white P..K = kinds 0-5, black = 6-11, 0x88
// squares), plus side-to-move, castling-rights, and ep-file keys, and
// the lookup tables that turn a piece byte into plane pointers:
// KINDTAB[piece&$0F] -> kind, ZPLLO[kind] -> pointer lo byte,
// ZPLHI0..3[kind] -> pointer hi byte per plane.
func emitZobrist(b *strings.Builder) {
	rnd := rand.New(rand.NewPCG(0x6502c4e5, 0x0a11babe))
	key := func() [4]byte {
		v := rnd.Uint32()
		return [4]byte{byte(v), byte(v >> 8), byte(v >> 16), byte(v >> 24)}
	}

	var planes [4][12 * 128]byte
	for kind := range 12 {
		for sq := range 128 {
			if sq&0x88 != 0 {
				continue
			}
			k := key()
			for p := range 4 {
				planes[p][kind*128+sq] = k[p]
			}
		}
	}
	names := []string{"ZPLANE0", "ZPLANE1", "ZPLANE2", "ZPLANE3"}
	for p, name := range names {
		b.WriteString("\n.align 256\n")
		emit(b, name, planes[p][:])
	}

	// KINDTAB: piece&$0F -> kind (color*6 + type-1); $FF for invalid.
	var kindTab [16]byte
	for i := range kindTab {
		kindTab[i] = 0xFF
	}
	for typ := 1; typ <= 6; typ++ {
		kindTab[typ] = byte(typ - 1)
		kindTab[8|typ] = byte(6 + typ - 1)
	}
	emit(b, "KINDTAB", kindTab[:])
	// Plane pointer tables: block = kind*128 within each 1536-byte plane.
	b.WriteString("ZPLLO:\n        .byte ")
	for kind := range 12 {
		if kind > 0 {
			b.WriteString(",")
		}
		fmt.Fprintf(b, "$%02X", (kind&1)*128)
	}
	b.WriteString("\n")
	for p, name := range names {
		fmt.Fprintf(b, "ZPLHI%d:\n        .byte ", p)
		for kind := range 12 {
			if kind > 0 {
				b.WriteString(",")
			}
			fmt.Fprintf(b, ">%s+%d", name, kind/2)
		}
		b.WriteString("\n")
	}

	stm := key()
	fmt.Fprintf(b, "STMKEY:\n        .byte $%02X,$%02X,$%02X,$%02X\n",
		stm[0], stm[1], stm[2], stm[3])
	// Castling keys: one 4-byte key per rights nibble value.
	b.WriteString("CASTKEYS:\n")
	for range 16 {
		k := key()
		fmt.Fprintf(b, "        .byte $%02X,$%02X,$%02X,$%02X\n", k[0], k[1], k[2], k[3])
	}
	// EP keys: by file; plus EPNONE = 0 handled by skipping the xor.
	b.WriteString("EPKEYS:\n")
	for range 8 {
		k := key()
		fmt.Fprintf(b, "        .byte $%02X,$%02X,$%02X,$%02X\n", k[0], k[1], k[2], k[3])
	}
}

func emitInts(b *strings.Builder, name string, offs []int) {
	fmt.Fprintf(b, "%s:\n        .byte ", name)
	for i, o := range offs {
		if i > 0 {
			b.WriteString(",")
		}
		fmt.Fprintf(b, "$%02X", byte(o&0xFF))
	}
	b.WriteString("\n")
}
