// Command gentables generates asm/tables.s: the 0x88 difference-indexed
// attack and direction tables, castling-rights masks, and piece offset
// tables. Run via `make tables` (or `go run ./cmd/gentables` directly).
//
// Difference tables are indexed by (to - from + $77) & $FF for squares in
// 0x88 coordinates. ATTACKTAB holds a bitmask of piece kinds that could
// attack across that difference on an empty board; DELTATAB holds the
// single-step delta (as an unsigned byte) toward `to` for slider rays,
// or 0 if the difference is not on any ray.
package main

import (
	"fmt"
	"math/rand/v2"
	"os"
	"strings"
)

const (
	atkKnight    = 1 << 0
	atkKing      = 1 << 1
	atkDiag      = 1 << 2 // bishop or queen
	atkOrtho     = 1 << 3 // rook or queen
	atkWPawn     = 1 << 4 // white pawn capture (moving up: +$0F/+$11)
	atkBPawn     = 1 << 5 // black pawn capture (moving down: -$0F/-$11)
	tableComment = "; Generated by cmd/gentables. DO NOT EDIT.\n"
)

var (
	knightOffs = []int{-33, -31, -18, -14, 14, 18, 31, 33}
	kingOffs   = []int{-17, -16, -15, -1, 1, 15, 16, 17}
	diagOffs   = []int{-17, -15, 15, 17}
	orthoOffs  = []int{-16, -1, 1, 16}
)

func onBoard(sq int) bool { return sq >= 0 && sq < 128 && sq&0x88 == 0 }

func main() {
	var attack [256]byte
	var delta [256]byte

	for from := range 128 {
		if !onBoard(from) {
			continue
		}
		mark := func(to int, bit byte, step int) {
			if !onBoard(to) {
				return
			}
			idx := (to - from + 0x77) & 0xFF
			attack[idx] |= bit
			if step != 0 {
				delta[idx] = byte(step & 0xFF)
			}
		}
		for _, o := range knightOffs {
			mark(from+o, atkKnight, 0)
		}
		for _, o := range kingOffs {
			mark(from+o, atkKing, 0)
		}
		for _, o := range diagOffs {
			for to := from + o; onBoard(to); to += o {
				mark(to, atkDiag, o)
			}
		}
		for _, o := range orthoOffs {
			for to := from + o; onBoard(to); to += o {
				mark(to, atkOrtho, o)
			}
		}
		mark(from+0x0F, atkWPawn, 0)
		mark(from+0x11, atkWPawn, 0)
		mark(from-0x0F, atkBPawn, 0)
		mark(from-0x11, atkBPawn, 0)
	}

	// Castling-rights mask: rights bits to KEEP when a square is touched
	// (moved from or captured on). Bits: 1=WK, 2=WQ, 4=BK, 8=BQ.
	var castleMask [128]byte
	for i := range castleMask {
		castleMask[i] = 0x0F
	}
	castleMask[0x04] = 0x0C // e1: white loses both
	castleMask[0x00] = 0x0D // a1: white loses queenside
	castleMask[0x07] = 0x0E // h1: white loses kingside
	castleMask[0x74] = 0x03 // e8: black loses both
	castleMask[0x70] = 0x07 // a8: black loses queenside
	castleMask[0x77] = 0x0B // h8: black loses kingside

	var b strings.Builder
	b.WriteString(tableComment)
	b.WriteString("\n.segment \"TABLES\"\n\n.align 256\n")
	emit(&b, "ATTACKTAB", attack[:])
	b.WriteString("\n.align 256\n")
	emit(&b, "DELTATAB", delta[:])

	// SLOTTAB[b] = piece-list slot for piece byte b: index | (color ? 16 : 0).
	// Page-aligned so lda SLOTTAB,y never crosses.
	var slotTab [256]byte
	for i := range slotTab {
		s := i >> 4
		if i&8 != 0 {
			s |= 16
		}
		slotTab[i] = byte(s)
	}
	b.WriteString("\n.align 256\n")
	emit(&b, "SLOTTAB", slotTab[:])

	// TYPEATK2[piece&$0F] = the attack bit this piece contributes.
	// Pawns get their color's direction bit, so wrong-direction pawns
	// fast-reject through the same AND as every other piece — no
	// special case in attacked(). (Starts page-aligned after SLOTTAB.)
	var typeAtk2 [16]byte
	atkBits := []byte{0, 0 /*per color below*/, atkKnight, atkDiag, atkOrtho, atkDiag | atkOrtho, atkKing, 0}
	for typ := 1; typ <= 6; typ++ {
		typeAtk2[typ] = atkBits[typ]
		typeAtk2[8|typ] = atkBits[typ]
	}
	typeAtk2[1] = atkWPawn
	typeAtk2[8|1] = atkBPawn
	emit(&b, "TYPEATK2", typeAtk2[:])

	// Pawn-structure tables (pawnterm's rank-bitmask form). Per file,
	// pawnterm builds an 8-bit mask of occupied ranks; these tables
	// turn one mask into the derived quantities directly:
	//   RANKBIT[sq]   = 1 << rank (0x88-indexed board square)
	//   WBLOCKM[bits] = ranks >= the most advanced white pawn (its own
	//                   rank included: an adjacent same-rank enemy pawn
	//                   blocks, matching the old >= compare)
	//   WPASSB[bits]  = PASSEDBONUS[rank of most advanced white pawn]
	//   BBLOCKM[bits] = ranks <= the most advanced black pawn (ditto <=)
	//   BPASSB[bits]  = PASSEDBONUS[7 - that rank]
	// The passed-pawn bonus weights live HERE now. Values are the
	// Texel-tuned set from the Go mirror (validated +18 +/- 17 vs
	// no-pstruct over 800 mirror games; see docs/results.md).
	passedBonus := []int{0, 18, 0, 33, 62, 69, 28, 0}
	var rankBit [128]byte
	for sq := range rankBit {
		if sq&0x88 == 0 {
			rankBit[sq] = 1 << (sq >> 4)
		}
	}
	var wBlockM, wPassB, bBlockM, bPassB [256]byte
	for bits := 1; bits < 256; bits++ {
		hi := 7
		for bits&(1<<hi) == 0 {
			hi--
		}
		lo := 0
		for bits&(1<<lo) == 0 {
			lo++
		}
		wBlockM[bits] = byte(0xFF << hi)
		wPassB[bits] = byte(passedBonus[hi])
		bBlockM[bits] = byte(1<<(lo+1) - 1)
		bPassB[bits] = byte(passedBonus[7-lo])
	}
	b.WriteString("\n.align 256\n")
	emit(&b, "RANKBIT", rankBit[:])
	emit(&b, "WBLOCKM", wBlockM[:])
	b.WriteString("\n.align 256\n")
	emit(&b, "WPASSB", wPassB[:])
	b.WriteString("\n.align 256\n")
	emit(&b, "BBLOCKM", bBlockM[:])
	b.WriteString("\n.align 256\n")
	emit(&b, "BPASSB", bPassB[:])

	// TT addressing: TTPTR = TTBASE + index*8, index = (HASH1&0x0F)<<8 | HASH0.
	// SHL3TAB/SHR5TAB split HASH0*8 across the pointer bytes; TTHITAB puts
	// HASH1's nibble in bits 3-6. Page-aligned so lda abs,x never crosses.
	var shl3Tab, shr5Tab, ttHiTab [256]byte
	for i := range shl3Tab {
		shl3Tab[i] = byte(i << 3)
		shr5Tab[i] = byte(i >> 5)
		ttHiTab[i] = byte((i & 0x0F) << 3)
	}
	b.WriteString("\n.align 256\n")
	emit(&b, "SHL3TAB", shl3Tab[:])
	b.WriteString("\n.align 256\n")
	emit(&b, "SHR5TAB", shr5Tab[:])
	b.WriteString("\n.align 256\n")
	emit(&b, "TTHITAB", ttHiTab[:])
	b.WriteString("\n.align 128\n")
	emit(&b, "CASTLEMASK", castleMask[:])
	b.WriteString("\n")
	emitInts(&b, "KNIGHTOFF", knightOffs)
	emitInts(&b, "KINGOFF", kingOffs)
	emitInts(&b, "DIAGOFF", diagOffs)
	emitInts(&b, "ORTHOOFF", orthoOffs)
	emitPSQT(&b)
	emitZobrist(&b)

	if err := os.WriteFile("asm/tables.s", []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func emit(b *strings.Builder, name string, data []byte) {
	fmt.Fprintf(b, "%s:\n", name)
	for i := 0; i < len(data); i += 16 {
		b.WriteString("        .byte ")
		for j := i; j < i+16 && j < len(data); j++ {
			if j > i {
				b.WriteString(",")
			}
			fmt.Fprintf(b, "$%02X", data[j])
		}
		b.WriteString("\n")
	}
}

// emitPSQT writes the tapered piece-square tables in the engine's layout:
// for piece type t (1-6), a 512-byte block at PSQTBASE+(t-1)*512 holding
// MGLO[sq88] at +0, MGHI at +128, EGLO at +256, EGHI at +384. Values are
// white-POV with piece base values baked in; black uses sq^$70 and
// subtracts. TYPEPAGE0/1 give each type's table page for (zp),y access;
// they are emitted as link-time expressions on PSQTBASE.
func emitPSQT(b *strings.Builder) {
	b.WriteString("\n.align 256\nPSQTBASE:\n")
	for t := range 6 {
		var mglo, mghi, eglo, eghi [128]byte
		for sq := range 128 {
			if sq&0x88 != 0 {
				continue
			}
			rank := sq >> 4
			file := sq & 7
			idx := (7-rank)*8 + file // PeSTO tables are a8-first
			mg := pestoPieceMG[t] + pestoMG[t][idx]
			eg := pestoPieceEG[t] + pestoEG[t][idx]
			mglo[sq] = byte(mg & 0xFF)
			mghi[sq] = byte(mg >> 8 & 0xFF)
			eglo[sq] = byte(eg & 0xFF)
			eghi[sq] = byte(eg >> 8 & 0xFF)
		}
		names := []string{"PAWN", "KNIGHT", "BISHOP", "ROOK", "QUEEN", "KING"}
		emit(b, fmt.Sprintf("PSQT_%s_MGLO", names[t]), mglo[:])
		emit(b, fmt.Sprintf("PSQT_%s_MGHI", names[t]), mghi[:])
		emit(b, fmt.Sprintf("PSQT_%s_EGLO", names[t]), eglo[:])
		emit(b, fmt.Sprintf("PSQT_%s_EGHI", names[t]), eghi[:])
	}
	// Table page pointers, indexed by piece type 1-6 (0 and 7 unused).
	b.WriteString("\nTYPEPAGE0:\n        .byte 0")
	for t := range 6 {
		fmt.Fprintf(b, ", >PSQTBASE+%d", t*2)
	}
	b.WriteString(", 0\nTYPEPAGE1:\n        .byte 0")
	for t := range 6 {
		fmt.Fprintf(b, ", >PSQTBASE+%d", t*2+1)
	}
	b.WriteString(", 0\n")
	// Phase contribution per piece type, and phase -> /32 taper weight.
	b.WriteString("PHASEVAL:\n        .byte 0,0,1,1,2,4,0,0\n")
	b.WriteString("PHASEW:\n        .byte ")
	for p := 0; p <= 24; p++ {
		if p > 0 {
			b.WriteString(",")
		}
		fmt.Fprintf(b, "%d", (p*32+12)/24)
	}
	b.WriteString("\n")
}

// emitZobrist writes 32-bit Zobrist keys kind-major: ZKEYS + kind*512
// holds plane0[128] plane1[128] plane2[128] plane3[128] for that kind
// (white P..K = kinds 0-5, black = 6-11, 0x88 squares). Every block
// starts on a page boundary, so a pointer to it has lo byte 0 — the
// ZPTR invariant established in evalinit. ZKHI0[piece&$0F] gives the
// block's page directly; DIRTYTAB/TYPEPG0X/TYPEPG1X/PHASEV16 are
// companion piece&$0F-indexed tables for the fused make-path updates.
// Also emitted: side-to-move, castling-rights, and ep-file keys.
func emitZobrist(b *strings.Builder) {
	rnd := rand.New(rand.NewPCG(0x6502c4e5, 0x0a11babe))
	key := func() [4]byte {
		v := rnd.Uint32()
		return [4]byte{byte(v), byte(v >> 8), byte(v >> 16), byte(v >> 24)}
	}

	var keys [12 * 512]byte
	for kind := range 12 {
		for sq := range 128 {
			if sq&0x88 != 0 {
				continue
			}
			k := key()
			for p := range 4 {
				keys[kind*512+p*128+sq] = k[p]
			}
		}
	}
	b.WriteString("\n.align 256\n")
	emit(b, "ZKEYS", keys[:])

	// The piece&$0F-indexed tables (color bit 3 + type bits 0-2).
	pieceIdx := func(name string, val func(typ, kind int) string) {
		fmt.Fprintf(b, "%s:\n        .byte ", name)
		for i := range 16 {
			if i > 0 {
				b.WriteString(",")
			}
			typ := i & 7
			if typ < 1 || typ > 6 {
				b.WriteString("0")
				continue
			}
			kind := typ - 1
			if i&8 != 0 {
				kind += 6
			}
			b.WriteString(val(typ, kind))
		}
		b.WriteString("\n")
	}
	pieceIdx("ZKHI0", func(typ, kind int) string {
		return fmt.Sprintf(">ZKEYS+%d", kind*2)
	})
	pieceIdx("DIRTYTAB", func(typ, kind int) string {
		if typ == 1 || typ == 6 { // pawn or king: invalidate PSTRUCT
			return "1"
		}
		return "0"
	})
	pieceIdx("TYPEPG0X", func(typ, kind int) string {
		return fmt.Sprintf(">PSQTBASE+%d", (typ-1)*2)
	})
	pieceIdx("TYPEPG1X", func(typ, kind int) string {
		return fmt.Sprintf(">PSQTBASE+%d", (typ-1)*2+1)
	})
	phaseVals := []int{0, 0, 1, 1, 2, 4, 0, 0}
	pieceIdx("PHASEV16", func(typ, kind int) string {
		return fmt.Sprintf("%d", phaseVals[typ])
	})

	stm := key()
	fmt.Fprintf(b, "STMKEY:\n        .byte $%02X,$%02X,$%02X,$%02X\n",
		stm[0], stm[1], stm[2], stm[3])
	// Unrolled side-to-move hash update (runs on every make/unmakenull;
	// the immediate forms halve the looped version's cost).
	b.WriteString("hashstm:\n")
	for i, kb := range stm {
		fmt.Fprintf(b, "        lda HASH%d\n        eor #$%02X\n        sta HASH%d\n", i, kb, i)
	}
	b.WriteString("        rts\n")
	// Castling keys: one 4-byte key per rights nibble value.
	b.WriteString("CASTKEYS:\n")
	for range 16 {
		k := key()
		fmt.Fprintf(b, "        .byte $%02X,$%02X,$%02X,$%02X\n", k[0], k[1], k[2], k[3])
	}
	// EP keys: by file; plus EPNONE = 0 handled by skipping the xor.
	b.WriteString("EPKEYS:\n")
	for range 8 {
		k := key()
		fmt.Fprintf(b, "        .byte $%02X,$%02X,$%02X,$%02X\n", k[0], k[1], k[2], k[3])
	}
}

func emitInts(b *strings.Builder, name string, offs []int) {
	fmt.Fprintf(b, "%s:\n        .byte ", name)
	for i, o := range offs {
		if i > 0 {
			b.WriteString(",")
		}
		fmt.Fprintf(b, "$%02X", byte(o&0xFF))
	}
	b.WriteString("\n")
}
