// Command gentables generates asm/tables.s: the 0x88 difference-indexed
// attack and direction tables, castling-rights masks, and piece offset
// tables. Run via go:generate or `make tables`.
//
// Difference tables are indexed by (to - from + $77) & $FF for squares in
// 0x88 coordinates. ATTACKTAB holds a bitmask of piece kinds that could
// attack across that difference on an empty board; DELTATAB holds the
// single-step delta (as an unsigned byte) toward `to` for slider rays,
// or 0 if the difference is not on any ray.
package main

import (
	"fmt"
	"os"
	"strings"
)

const (
	atkKnight    = 1 << 0
	atkKing      = 1 << 1
	atkDiag      = 1 << 2 // bishop or queen
	atkOrtho     = 1 << 3 // rook or queen
	atkWPawn     = 1 << 4 // white pawn capture (moving up: +$0F/+$11)
	atkBPawn     = 1 << 5 // black pawn capture (moving down: -$0F/-$11)
	tableComment = "; Generated by cmd/gentables. DO NOT EDIT.\n"
)

var (
	knightOffs = []int{-33, -31, -18, -14, 14, 18, 31, 33}
	kingOffs   = []int{-17, -16, -15, -1, 1, 15, 16, 17}
	diagOffs   = []int{-17, -15, 15, 17}
	orthoOffs  = []int{-16, -1, 1, 16}
)

func onBoard(sq int) bool { return sq >= 0 && sq < 128 && sq&0x88 == 0 }

func main() {
	var attack [256]byte
	var delta [256]byte

	for from := range 128 {
		if !onBoard(from) {
			continue
		}
		mark := func(to int, bit byte, step int) {
			if !onBoard(to) {
				return
			}
			idx := (to - from + 0x77) & 0xFF
			attack[idx] |= bit
			if step != 0 {
				delta[idx] = byte(step & 0xFF)
			}
		}
		for _, o := range knightOffs {
			mark(from+o, atkKnight, 0)
		}
		for _, o := range kingOffs {
			mark(from+o, atkKing, 0)
		}
		for _, o := range diagOffs {
			for to := from + o; onBoard(to); to += o {
				mark(to, atkDiag, o)
			}
		}
		for _, o := range orthoOffs {
			for to := from + o; onBoard(to); to += o {
				mark(to, atkOrtho, o)
			}
		}
		mark(from+0x0F, atkWPawn, 0)
		mark(from+0x11, atkWPawn, 0)
		mark(from-0x0F, atkBPawn, 0)
		mark(from-0x11, atkBPawn, 0)
	}

	// Castling-rights mask: rights bits to KEEP when a square is touched
	// (moved from or captured on). Bits: 1=WK, 2=WQ, 4=BK, 8=BQ.
	var castleMask [128]byte
	for i := range castleMask {
		castleMask[i] = 0x0F
	}
	castleMask[0x04] = 0x0C // e1: white loses both
	castleMask[0x00] = 0x0D // a1: white loses queenside
	castleMask[0x07] = 0x0E // h1: white loses kingside
	castleMask[0x74] = 0x03 // e8: black loses both
	castleMask[0x70] = 0x07 // a8: black loses queenside
	castleMask[0x77] = 0x0B // h8: black loses kingside

	var b strings.Builder
	b.WriteString(tableComment)
	b.WriteString("\n.segment \"TABLES\"\n\n.align 256\n")
	emit(&b, "ATTACKTAB", attack[:])
	b.WriteString("\n.align 256\n")
	emit(&b, "DELTATAB", delta[:])
	b.WriteString("\n.align 128\n")
	emit(&b, "CASTLEMASK", castleMask[:])
	b.WriteString("\n")
	emitInts(&b, "KNIGHTOFF", knightOffs)
	emitInts(&b, "KINGOFF", kingOffs)
	emitInts(&b, "DIAGOFF", diagOffs)
	emitInts(&b, "ORTHOOFF", orthoOffs)

	if err := os.WriteFile("asm/tables.s", []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func emit(b *strings.Builder, name string, data []byte) {
	fmt.Fprintf(b, "%s:\n", name)
	for i := 0; i < len(data); i += 16 {
		b.WriteString("        .byte ")
		for j := i; j < i+16 && j < len(data); j++ {
			if j > i {
				b.WriteString(",")
			}
			fmt.Fprintf(b, "$%02X", data[j])
		}
		b.WriteString("\n")
	}
}

func emitInts(b *strings.Builder, name string, offs []int) {
	fmt.Fprintf(b, "%s:\n        .byte ", name)
	for i, o := range offs {
		if i > 0 {
			b.WriteString(",")
		}
		fmt.Fprintf(b, "$%02X", byte(o&0xFF))
	}
	b.WriteString("\n")
}
